### ISSUE TITLE
Automatically localize common html tags

### ISSUE THREAD

**Issue by MikeEsteves** [WormieCorp/Localization.AspNetCore.TagHelpers#17]
We going through the process of localizing all our views and this library makes it nice and easy. <localize>something</localize> is much easier than @Localizer["something"]. 

But then I was giving it some thought and was wondering why do we even need to <localize> tag. Would it be possible to override all other html tags, so `<div> <span> <p> <h1> <a>` etc and inject the localisation into those tags. Then any string within a view would be automatically localized without having to specify attributes?

I can't think of a use case where you wouldn't want to localize some things but would other things? But a <dont-localize> tag could be added so you could prevent localization in those cases. It could also be globally configurable in services.Configure and off by default as to not affect current users. 

Thoughts on this? If its something you feel you would add, I'll be happy to put together a pull request

Thanks
M

**Comment by AdmiringWorm** [comment]
While most of the tags would definitely make sense to automatically localize, there may be circumstances where a certain tag shouldn't be localzed (which is why I also added localization with the use of an attribute as well, `<h1 localize>Text to localize</h1>`).

Of course, it could easily be implemented an option to automatically localize a specific set of html tags (with an override to allow localization to be disable for a certain tag).

I need to think about this a little first though.
A workaround until I've decided if I want it in the library or not, is to create a new tag helper yourself and inherit it from the [GenericLocalizeTagHelper](https://github.com/WormieCorp/Localization.AspNetCore.TagHelpers/blob/master/src/Localization.AspNetCore.TagHelpers/GenericLocalizeTagHelper.cs) class (can't use the [LocalizeTagHelper](https://github.com/WormieCorp/Localization.AspNetCore.TagHelpers/blob/master/src/Localization.AspNetCore.TagHelpers/LocalizeTagHelper.cs) as this also removes the tag itself).

Small sample on what to add if you want support for it right now:
```cs
[HtmlTargetElement("h1")]
[HtmlTargetElement("span")]
// Every other tag you want to support
public class AutoLocalizeTagHelper : GenericLocalizeTagHelper
{
    public AutoLocalizeTagHelper(IHtmlLocalizerFactory localizerFactory, IHostingEnvironment hostingEnvironment, IOptions<LocalizeTagHelperOptions> options)
        : base(localizerFactory, hostingEnvironment, options)
    {
    }
}
```

I believe the above would be enough to support what you want.

**Comment by AdmiringWorm** [comment]
Seems like I missed the last paragraph of your comment.

I've also thought a little about this now, and I would love a PR for implementing such a thing.

Please read over our [Contribution Guidelines](https://github.com/WormieCorp/Localization.AspNetCore.TagHelpers/blob/master/CONTRIBUTING.md) before you open a PR though (you'll also need to sign our [CLA](https://cla-assistant.io/WormieCorp/Localization.AspNetCore.TagHelpers) before it's accepted, you'll be prompted for that when you open a PR).
